channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pytorch::pytorch
  - altair
  - anndata
  - dill
  - jupyterlab
  - matplotlib
  - mudata
  - numpy
  - pandas
  - pyro-ppl
  - pytest
  - ruff
  - scikit-learn
  - scipy
  - seaborn
  - tensordict
  - tqdm
  - scanpy
  - addict
  - vegafusion-python-embed[version='>
  - vegafusion[version='>
  - vl-convert-python[version='>
  - pipreqs
  - pip-tools
name: famo
